
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManager.DL.EntityDataModel
{

using System;
    using System.Collections.Generic;
    
public partial class T_TASK
{

    public int TASK_ID { get; set; }

    public string TASK_NM { get; set; }

    public Nullable<int> PARENT_TASK_ID { get; set; }

    public int PRIORITY { get; set; }

    public System.DateTime STRT_DT { get; set; }

    public System.DateTime END_DT { get; set; }

    public int PROJ_ID { get; set; }

    public int USR_ID { get; set; }

    public string STATUS { get; set; }



    public virtual T_PARENT_TASK T_PARENT_TASK { get; set; }

    public virtual T_PROJECT T_PROJECT { get; set; }

    public virtual T_USER T_USER { get; set; }

}

}
