
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectManager.DL.EntityDataModel
{

using System;
    using System.Collections.Generic;
    
public partial class T_USER
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public T_USER()
    {

        this.T_PROJECT = new HashSet<T_PROJECT>();

        this.T_TASK = new HashSet<T_TASK>();

    }


    public int EMP_ID { get; set; }

    public string EMP_FRST_NM { get; set; }

    public string EMP_LST_NM { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_PROJECT> T_PROJECT { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<T_TASK> T_TASK { get; set; }

}

}
